project:
  type: website
  output-dir: docs

book:
  title: "CASA0025 Final Assessment"
  author: "Group Name"
  date: "29/04/2026"
  chapters:
    - index.qmd

  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: favicon.ico
  sidebar:
    logo: casa_logo.png



format:
  html:
    theme:
      dark: darkly
      light: litera
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"
    toc: true
    toc-title: "Comfort Path: an Interactive Walking Route Finder"
    toc-depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
